### ISSUE TITLE
Installer breaks due to ifconfig not found

### ISSUE THREAD

**Issue by oskarryn** [hadoopsubmarine/submarine-installer#1]
When running the `submarine-installer/install.sh command` on CentOS 7.6.1811 ("centos/7" vagrant box) there is an error:

```
/home/hadoop/submarine-installer/scripts/utils.sh: line 192: ifconfig: command not found
```

I reckon that on newer centos `ifconfig` is now `ip a`. It breaks the scripts for newer releases than `centos-release-7-3.1611.el7.centos.x86_64` (not sure from which one, but it doesn't work on 7.6.1811)

ps. you could just precise that it must be `centos-release-7-3.1611.el7.centos.x86_64`

**Comment by yuanzac** [comment]
@oskarryn,
Thanks a lot for pointing out the issue.
Fix it using ip instead of ifconfig
