### ISSUE TITLE
Cannot use the installer without Kerberos configuration

### ISSUE THREAD

**Issue by oskarryn** [hadoopsubmarine/submarine-installer#2]
When launching the `submarine-installer/install.sh`, it stops due to the empty `LOCAL_REALM`.

Could you advice me on the desired content of the `LOCAL_REALM` in the `instal.conf`? Ideally, I'd skip that along the YARN-kerberos configuration. However, it seems that I cannot use the installer without Kerberos. Could I work around this somehow?

**Comment by yuanzac** [comment]
Close it now, If there is any other issue, feel free to reopen it.~
